### ISSUE TITLE
Link is not properly formated

### ISSUE THREAD

**Issue by nawarajshah** [computerclubkec/oop#22]
Description:
I tried to open some of the links on the [project page](https://github.com/computerclubkec/oop/tree/master/projects) but was unable to open it. It gives me a 404 error.

Steps to Reproduce:

Step 1: Go to this [link](https://github.com/computerclubkec/oop/tree/master/projects)
Step 2: Try to open **Online Quiz application** and it gives a 404 error.

Expected Behavior:
Should open related page or repo

Actual Behavior:
Gives 404 error

Screenshots:
<img width="700" alt="image" src="https://github.com/computerclubkec/oop/assets/11453784/838aab0c-7a44-45b2-8d0f-72e5f188e764">

**Comment by thegauravgiri** [comment]
Oh yes, I forgot about it. Those are just idea lists for now. 
It can be solved in either of the two ways:
1. Remove links from each
2. or Redirect the link to a github search page with related keywords to list related projects.
